// example/outputs/test.vue
<template>
  <div>
    <h1 id="a-bright-sun">A bright sun</h1>
    <h2 id="the-day-i-was-born">The day I was born</h2>
    <p>It was in the year <strong>503</strong>, once...</p>
    <blockquote>
      <p><em>They should be all damned</em></p>
    </blockquote>
    <p><img src="test-image.png" alt="test image" /></p>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { Component } from 'vue-property-decorator'

@Component
export default class Test extends Vue {}
</script>

// example/outputs/test.svelte
<div>
  <h1 id="a-bright-sun">A bright sun</h1>
  <h2 id="the-day-i-was-born">The day I was born</h2>
  <p>It was in the year <strong>503</strong>, once...</p>
  <blockquote>
    <p><em>They should be all damned</em></p>
  </blockquote>
  <p>
    <img src="test-image.png" alt="test image">
  </p>
</div>

<script lang="ts">  
</script>
